server:
  port: 8080
  servlet:
    context-path: /api/@api.version@

game:
  port: 2000
  players: 4

spring:
  datasource:
    url: jdbc:postgresql:whoami
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate